// GENERATED by tools/build_manifest.py — regenerate rather than hand-editing
// entries. Colliders are alpha-derived native-px rects relative to the piece
// top-left; 'deco'/'bird'/'fx' families never collide.

export interface ArtRect {
  x: number
  y: number
  w: number
  h: number
}

export interface ArtPiece {
  key: string
  file: string
  w: number
  h: number
  family: 'bird' | 'arch' | 'windows' | 'split' | 'column' | 'wall' | 'hang' | 'organic' | 'organic-brittle' | 'organic-hang' | 'fx' | 'deco'
  colliders: ArtRect[]
  openings: ArtRect[]
}

export const ART: Record<string, ArtPiece> = {
  'bird-up': { key: 'bird-up', file: 'assets/processed/birds/navy_bird_flight_sprite_sheet__09.png', w: 112, h: 116, family: 'bird', colliders: [], openings: [] },
  'bird-mid': { key: 'bird-mid', file: 'assets/processed/birds/navy_bird_flight_sprite_sheet__10.png', w: 116, h: 56, family: 'bird', colliders: [], openings: [] },
  'bird-down': { key: 'bird-down', file: 'assets/processed/birds/navy_bird_flight_sprite_sheet__11.png', w: 112, h: 84, family: 'bird', colliders: [], openings: [] },
  'aqueduct_run': { key: 'aqueduct_run', file: 'assets/processed/ruins/ruined_violet_arch_tileset__00.png', w: 432, h: 208, family: 'wall', colliders: [{"x": 0, "y": 52, "w": 432, "h": 21}], openings: [] },
  'rose_wall': { key: 'rose_wall', file: 'assets/processed/ruins/ruined_violet_arch_tileset__02.png', w: 240, h: 196, family: 'windows', colliders: [{"x": 0, "y": 103, "w": 240, "h": 93}], openings: [] },
  'gate_double': { key: 'gate_double', file: 'assets/processed/ruins/ruined_violet_arch_tileset__04.png', w: 216, h: 184, family: 'split', colliders: [{"x": 0, "y": 10, "w": 216, "h": 31}, {"x": 0, "y": 61, "w": 216, "h": 123}], openings: [] },
  'wall_four_arch': { key: 'wall_four_arch', file: 'assets/processed/ruins/ruined_violet_arch_tileset__05.png', w: 307, h: 168, family: 'windows', colliders: [{"x": 0, "y": 32, "w": 307, "h": 42}, {"x": 0, "y": 126, "w": 307, "h": 42}], openings: [{"x": 76, "y": 68, "w": 28, "h": 80}, {"x": 140, "y": 72, "w": 24, "h": 76}, {"x": 200, "y": 72, "w": 28, "h": 76}] },
  'window_column': { key: 'window_column', file: 'assets/processed/ruins/ruined_violet_arch_tileset__06.png', w: 92, h: 180, family: 'column', colliders: [{"x": 0, "y": 20, "w": 92, "h": 20}, {"x": 0, "y": 50, "w": 92, "h": 60}, {"x": 0, "y": 130, "w": 92, "h": 50}], openings: [] },
  'wall_multi_window': { key: 'wall_multi_window', file: 'assets/processed/ruins/ruined_violet_arch_tileset__08.png', w: 316, h: 160, family: 'windows', colliders: [{"x": 0, "y": 40, "w": 316, "h": 60}, {"x": 0, "y": 140, "w": 316, "h": 20}], openings: [] },
  'aqueduct_slope': { key: 'aqueduct_slope', file: 'assets/processed/ruins/ruined_violet_arch_tileset__09.png', w: 200, h: 164, family: 'wall', colliders: [{"x": 0, "y": 102, "w": 200, "h": 62}], openings: [{"x": 120, "y": 68, "w": 24, "h": 80}] },
  'wall_arch_window': { key: 'wall_arch_window', file: 'assets/processed/ruins/ruined_violet_arch_tileset__12.png', w: 276, h: 152, family: 'windows', colliders: [{"x": 0, "y": 101, "w": 276, "h": 51}], openings: [] },
  'colonnade_arch': { key: 'colonnade_arch', file: 'assets/processed/ruins/ruined_violet_arch_tileset__15.png', w: 284, h: 140, family: 'arch', colliders: [{"x": 0, "y": 100, "w": 284, "h": 40}], openings: [] },
  'wall_two_window': { key: 'wall_two_window', file: 'assets/processed/ruins/ruined_violet_arch_tileset__18.png', w: 192, h: 120, family: 'windows', colliders: [{"x": 0, "y": 60, "w": 192, "h": 60}], openings: [] },
  'wall_double_arch': { key: 'wall_double_arch', file: 'assets/processed/ruins/ruined_violet_arch_tileset__21.png', w: 324, h: 112, family: 'wall', colliders: [{"x": 0, "y": 61, "w": 324, "h": 51}], openings: [] },
  'wheel_diagonal': { key: 'wheel_diagonal', file: 'assets/processed/ruins/ruined_violet_arch_tileset__24.png', w: 224, h: 116, family: 'wall', colliders: [{"x": 0, "y": 74, "w": 224, "h": 42}], openings: [] },
  'triple_column': { key: 'triple_column', file: 'assets/processed/ruins/ruined_violet_arch_tileset__31.png', w: 140, h: 108, family: 'split', colliders: [{"x": 0, "y": 11, "w": 140, "h": 22}], openings: [] },
  'twin_arch': { key: 'twin_arch', file: 'assets/processed/ruins/ruined_violet_arch_tileset__34.png', w: 144, h: 112, family: 'arch', colliders: [{"x": 0, "y": 0, "w": 144, "h": 20}], openings: [] },
  'arch_fragment': { key: 'arch_fragment', file: 'assets/processed/ruins/ruined_violet_arch_tileset__36.png', w: 88, h: 105, family: 'arch', colliders: [{"x": 0, "y": 10, "w": 88, "h": 94}], openings: [{"x": 32, "y": 20, "w": 28, "h": 76}] },
  'bridge_span': { key: 'bridge_span', file: 'assets/processed/ruins/ruined_violet_arch_tileset__41.png', w: 184, h: 69, family: 'wall', colliders: [{"x": 0, "y": 0, "w": 184, "h": 34}], openings: [] },
  'pillar_a': { key: 'pillar_a', file: 'assets/processed/ruins/ruined_violet_arch_tileset__28.png', w: 81, h: 120, family: 'column', colliders: [{"x": 0, "y": 20, "w": 81, "h": 100}], openings: [] },
  'pillar_b': { key: 'pillar_b', file: 'assets/processed/ruins/ruined_violet_arch_tileset__39.png', w: 92, h: 120, family: 'column', colliders: [{"x": 0, "y": 20, "w": 92, "h": 30}, {"x": 0, "y": 70, "w": 92, "h": 50}], openings: [] },
  'pillar_c': { key: 'pillar_c', file: 'assets/processed/ruins/ruined_violet_arch_tileset__43.png', w: 71, h: 120, family: 'column', colliders: [{"x": 0, "y": 30, "w": 71, "h": 90}], openings: [] },
  'ceiling_stub_a': { key: 'ceiling_stub_a', file: 'assets/processed/ruins/ruined_violet_arch_tileset__27.png', w: 164, h: 68, family: 'hang', colliders: [{"x": 0, "y": 0, "w": 164, "h": 45}], openings: [] },
  'ceiling_stub_b': { key: 'ceiling_stub_b', file: 'assets/processed/ruins/ruined_violet_arch_tileset__35.png', w: 132, h: 61, family: 'hang', colliders: [{"x": 0, "y": 0, "w": 132, "h": 41}], openings: [] },
  'ceiling_stub_c': { key: 'ceiling_stub_c', file: 'assets/processed/ruins/ruined_violet_arch_tileset__45.png', w: 136, h: 69, family: 'hang', colliders: [{"x": 0, "y": 0, "w": 136, "h": 46}], openings: [] },
  'grand_arch': { key: 'grand_arch', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__00.png', w: 348, h: 276, family: 'arch', colliders: [{"x": 0, "y": 20, "w": 348, "h": 51}], openings: [] },
  'gothic_arch': { key: 'gothic_arch', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__01.png', w: 220, h: 284, family: 'arch', colliders: [{"x": 0, "y": 254, "w": 220, "h": 30}], openings: [] },
  'double_arch_wall': { key: 'double_arch_wall', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__02.png', w: 388, h: 224, family: 'split', colliders: [{"x": 0, "y": 20, "w": 388, "h": 61}, {"x": 0, "y": 204, "w": 388, "h": 20}], openings: [] },
  'triple_window_wall': { key: 'triple_window_wall', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__06.png', w: 280, h: 196, family: 'windows', colliders: [{"x": 0, "y": 31, "w": 280, "h": 41}, {"x": 0, "y": 144, "w": 280, "h": 52}], openings: [{"x": 92, "y": 64, "w": 24, "h": 100}, {"x": 148, "y": 64, "w": 24, "h": 100}, {"x": 204, "y": 64, "w": 24, "h": 100}] },
  'rose_window_big': { key: 'rose_window_big', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__07.png', w: 292, h: 236, family: 'windows', colliders: [{"x": 0, "y": 92, "w": 292, "h": 21}, {"x": 0, "y": 144, "w": 292, "h": 72}], openings: [] },
  'tall_shard': { key: 'tall_shard', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__08.png', w: 116, h: 220, family: 'column', colliders: [{"x": 0, "y": 160, "w": 116, "h": 60}], openings: [] },
  'pointed_arch': { key: 'pointed_arch', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__12.png', w: 212, h: 252, family: 'arch', colliders: [{"x": 0, "y": 212, "w": 212, "h": 40}], openings: [{"x": 68, "y": 72, "w": 48, "h": 148}] },
  'triple_arcade': { key: 'triple_arcade', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__13.png', w: 308, h: 216, family: 'split', colliders: [{"x": 0, "y": 21, "w": 308, "h": 41}, {"x": 0, "y": 195, "w": 308, "h": 21}], openings: [] },
  'bent_arch': { key: 'bent_arch', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__14.png', w: 192, h: 228, family: 'arch', colliders: [{"x": 0, "y": 31, "w": 192, "h": 21}, {"x": 0, "y": 187, "w": 192, "h": 41}], openings: [] },
  'wall_arch_inset': { key: 'wall_arch_inset', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__16.png', w: 332, h: 220, family: 'arch', colliders: [{"x": 0, "y": 110, "w": 332, "h": 30}, {"x": 0, "y": 170, "w": 332, "h": 50}], openings: [] },
  'wall_circle_bite': { key: 'wall_circle_bite', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__19.png', w: 176, h: 212, family: 'windows', colliders: [{"x": 0, "y": 121, "w": 176, "h": 91}], openings: [] },
  'oval_window_wall': { key: 'oval_window_wall', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__20.png', w: 208, h: 164, family: 'windows', colliders: [{"x": 0, "y": 20, "w": 208, "h": 31}, {"x": 0, "y": 123, "w": 208, "h": 31}], openings: [{"x": 72, "y": 48, "w": 64, "h": 88}] },
  'tall_gate': { key: 'tall_gate', file: 'assets/processed/ruins/pastel_ruins_obstacle_sprite_sheet__21.png', w: 200, h: 212, family: 'arch', colliders: [{"x": 0, "y": 182, "w": 200, "h": 20}], openings: [] },
  'obelisk_a': { key: 'obelisk_a', file: 'assets/processed/ruins/pastel_ruined_architecture_sprite_sheet__08.png', w: 80, h: 316, family: 'column', colliders: [{"x": 0, "y": 31, "w": 80, "h": 285}], openings: [] },
  'obelisk_b': { key: 'obelisk_b', file: 'assets/processed/ruins/pastel_ruined_architecture_sprite_sheet__07.png', w: 84, h: 280, family: 'column', colliders: [{"x": 0, "y": 30, "w": 84, "h": 250}], openings: [] },
  'column_ring': { key: 'column_ring', file: 'assets/processed/ruins/pastel_ruined_architecture_sprite_sheet__18.png', w: 88, h: 292, family: 'column', colliders: [{"x": 0, "y": 70, "w": 88, "h": 222}], openings: [] },
  'column_broken': { key: 'column_broken', file: 'assets/processed/ruins/pastel_ruined_architecture_sprite_sheet__12.png', w: 96, h: 280, family: 'column', colliders: [{"x": 0, "y": 0, "w": 96, "h": 40}, {"x": 0, "y": 250, "w": 96, "h": 30}], openings: [] },
  'column_pair': { key: 'column_pair', file: 'assets/processed/ruins/pastel_ruined_architecture_sprite_sheet__31.png', w: 116, h: 244, family: 'split', colliders: [{"x": 0, "y": 0, "w": 116, "h": 20}, {"x": 0, "y": 41, "w": 116, "h": 203}], openings: [{"x": 52, "y": 16, "w": 20, "h": 188}] },
  'column_clean': { key: 'column_clean', file: 'assets/processed/ruins/pastel_ruined_architecture_sprite_sheet__06.png', w: 80, h: 272, family: 'column', colliders: [{"x": 0, "y": 0, "w": 80, "h": 40}, {"x": 0, "y": 252, "w": 80, "h": 20}], openings: [] },
  'keyhole_arch': { key: 'keyhole_arch', file: 'assets/processed/ruins/pastel_ruined_architecture_sprite_sheet__56.png', w: 276, h: 456, family: 'arch', colliders: [{"x": 0, "y": 0, "w": 276, "h": 20}, {"x": 0, "y": 385, "w": 276, "h": 71}], openings: [{"x": 72, "y": 304, "w": 20, "h": 128}] },
  'wisteria_curtain': { key: 'wisteria_curtain', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__01.png', w: 272, h: 256, family: 'organic-brittle', colliders: [{"x": 0, "y": 0, "w": 272, "h": 256}], openings: [] },
  'wisteria_dense': { key: 'wisteria_dense', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__02.png', w: 172, h: 264, family: 'organic-brittle', colliders: [{"x": 0, "y": 0, "w": 172, "h": 264}], openings: [] },
  'root_tangle': { key: 'root_tangle', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__03.png', w: 224, h: 280, family: 'organic-hang', colliders: [{"x": 0, "y": 10, "w": 224, "h": 20}], openings: [{"x": 48, "y": 40, "w": 68, "h": 180}] },
  'leaf_strand': { key: 'leaf_strand', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__04.png', w: 120, h: 228, family: 'organic-hang', colliders: [{"x": 0, "y": 10, "w": 120, "h": 21}, {"x": 0, "y": 62, "w": 120, "h": 104}], openings: [] },
  'ceiling_pods': { key: 'ceiling_pods', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__05.png', w: 248, h: 248, family: 'organic-hang', colliders: [{"x": 0, "y": 10, "w": 248, "h": 52}], openings: [] },
  'thorn_arc': { key: 'thorn_arc', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__06.png', w: 120, h: 204, family: 'organic', colliders: [{"x": 48, "y": 12, "w": 12, "h": 24}, {"x": 24, "y": 24, "w": 24, "h": 12}, {"x": 60, "y": 24, "w": 12, "h": 48}, {"x": 72, "y": 36, "w": 12, "h": 36}, {"x": 84, "y": 48, "w": 12, "h": 132}, {"x": 96, "y": 60, "w": 12, "h": 108}, {"x": 108, "y": 84, "w": 12, "h": 36}, {"x": 72, "y": 144, "w": 12, "h": 36}, {"x": 48, "y": 168, "w": 24, "h": 24}, {"x": 36, "y": 192, "w": 24, "h": 12}], openings: [] },
  'thorn_ring': { key: 'thorn_ring', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__07.png', w: 228, h: 208, family: 'organic', colliders: [{"x": 0, "y": 177, "w": 228, "h": 21}], openings: [{"x": 32, "y": 36, "w": 160, "h": 148}] },
  'lattice_gate': { key: 'lattice_gate', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__09.png', w: 216, h: 240, family: 'organic', colliders: [{"x": 0, "y": 80, "w": 216, "h": 150}], openings: [] },
  'wisteria_arch': { key: 'wisteria_arch', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__10.png', w: 196, h: 200, family: 'organic', colliders: [{"x": 0, "y": 10, "w": 196, "h": 80}], openings: [] },
  'web_column_a': { key: 'web_column_a', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__11.png', w: 128, h: 196, family: 'organic', colliders: [{"x": 0, "y": 134, "w": 128, "h": 21}, {"x": 0, "y": 165, "w": 128, "h": 31}], openings: [] },
  'web_column_b': { key: 'web_column_b', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__12.png', w: 120, h: 192, family: 'organic', colliders: [{"x": 0, "y": 101, "w": 120, "h": 20}, {"x": 0, "y": 141, "w": 120, "h": 20}, {"x": 0, "y": 172, "w": 120, "h": 20}], openings: [{"x": 8, "y": 48, "w": 56, "h": 52}] },
  'web_net': { key: 'web_net', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__13.png', w: 328, h: 180, family: 'organic-brittle', colliders: [{"x": 0, "y": 0, "w": 328, "h": 180}], openings: [{"x": 36, "y": 72, "w": 84, "h": 32}, {"x": 136, "y": 80, "w": 52, "h": 44}, {"x": 184, "y": 92, "w": 60, "h": 56}, {"x": 44, "y": 100, "w": 100, "h": 40}, {"x": 116, "y": 112, "w": 84, "h": 40}] },
  'branch_cluster': { key: 'branch_cluster', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__14.png', w: 272, h: 168, family: 'organic', colliders: [{"x": 0, "y": 84, "w": 272, "h": 42}], openings: [{"x": 100, "y": 12, "w": 60, "h": 36}] },
  'organic_arch': { key: 'organic_arch', file: 'assets/processed/organic/murmuration_ruins_organic_obstacle_asset_sheet__15.png', w: 220, h: 196, family: 'organic', colliders: [{"x": 0, "y": 21, "w": 220, "h": 31}, {"x": 0, "y": 165, "w": 220, "h": 21}], openings: [{"x": 164, "y": 84, "w": 40, "h": 80}] },
  'roost_tree': { key: 'roost_tree', file: 'assets/processed/ending/dreamy_ruins_flock_asset_sheet__08.png', w: 244, h: 168, family: 'deco', colliders: [], openings: [] },
  'flock_swirl': { key: 'flock_swirl', file: 'assets/processed/ending/dreamy_ruins_flock_asset_sheet__16.png', w: 180, h: 184, family: 'deco', colliders: [], openings: [] },
  'flock_decal_a': { key: 'flock_decal_a', file: 'assets/processed/ending/dreamy_ruins_flock_asset_sheet__11.png', w: 260, h: 108, family: 'deco', colliders: [], openings: [] },
  'flock_decal_b': { key: 'flock_decal_b', file: 'assets/processed/ending/dreamy_ruins_flock_asset_sheet__14.png', w: 212, h: 86, family: 'deco', colliders: [], openings: [] },
  'stray_glow': { key: 'stray_glow', file: 'assets/processed/ending/dreamy_ruins_flock_asset_sheet__17.png', w: 128, h: 128, family: 'deco', colliders: [], openings: [] },
  'spark_strand': { key: 'spark_strand', file: 'assets/processed/ending/dreamy_ruins_flock_asset_sheet__20.png', w: 40, h: 120, family: 'deco', colliders: [], openings: [] },
  'wind_stream_long': { key: 'wind_stream_long', file: 'assets/processed/fx/dreamy_pastel_wind_fx_sprite_sheet__01.png', w: 708, h: 84, family: 'fx', colliders: [], openings: [] },
  'wind_stream_wave': { key: 'wind_stream_wave', file: 'assets/processed/fx/dreamy_pastel_wind_fx_sprite_sheet__11.png', w: 604, h: 112, family: 'fx', colliders: [], openings: [] },
  'wind_cross': { key: 'wind_cross', file: 'assets/processed/fx/dreamy_pastel_wind_fx_sprite_sheet__04.png', w: 232, h: 92, family: 'fx', colliders: [], openings: [] },
  'cloud_curl': { key: 'cloud_curl', file: 'assets/processed/fx/dreamy_pastel_wind_fx_sprite_sheet__14.png', w: 192, h: 84, family: 'fx', colliders: [], openings: [] },
  'cloud_s': { key: 'cloud_s', file: 'assets/processed/fx/dreamy_pastel_wind_fx_sprite_sheet__15.png', w: 192, h: 80, family: 'fx', colliders: [], openings: [] },
  'glow_warm': { key: 'glow_warm', file: 'assets/processed/fx/dreamy_pastel_wind_fx_sprite_sheet__16.png', w: 108, h: 104, family: 'fx', colliders: [], openings: [] },
  'wisp_a': { key: 'wisp_a', file: 'assets/processed/fx/dreamy_pastel_wind_fx_sprite_sheet__02.png', w: 128, h: 20, family: 'fx', colliders: [], openings: [] },
  'wisp_b': { key: 'wisp_b', file: 'assets/processed/fx/dreamy_pastel_wind_fx_sprite_sheet__09.png', w: 92, h: 28, family: 'fx', colliders: [], openings: [] },
  'panorama_0': { key: 'panorama_0', file: 'assets/processed/environment/ethereal_violet_ruins_panorama__00.png', w: 1060, h: 340, family: 'deco', colliders: [], openings: [{"x": 332, "y": 152, "w": 112, "h": 36}, {"x": 712, "y": 232, "w": 80, "h": 28}] },
  'panorama_1': { key: 'panorama_1', file: 'assets/processed/environment/ethereal_violet_ruins_panorama__01.png', w: 96, h: 28, family: 'deco', colliders: [], openings: [] },
  'panorama_2': { key: 'panorama_2', file: 'assets/processed/environment/ethereal_violet_ruins_panorama__02.png', w: 674, h: 340, family: 'deco', colliders: [], openings: [{"x": 364, "y": 116, "w": 64, "h": 36}, {"x": 216, "y": 184, "w": 56, "h": 36}] },
  'panorama_3': { key: 'panorama_3', file: 'assets/processed/environment/ethereal_violet_ruins_panorama__03.png', w: 104, h: 36, family: 'deco', colliders: [], openings: [] },
  'panorama_4': { key: 'panorama_4', file: 'assets/processed/environment/ethereal_violet_ruins_panorama__04.png', w: 28, h: 80, family: 'deco', colliders: [], openings: [] },
  'panorama_5': { key: 'panorama_5', file: 'assets/processed/environment/ethereal_violet_ruins_panorama__05.png', w: 922, h: 288, family: 'deco', colliders: [], openings: [] },
  'panorama_6': { key: 'panorama_6', file: 'assets/processed/environment/ethereal_violet_ruins_panorama__06.png', w: 766, h: 256, family: 'deco', colliders: [], openings: [] },
  'bg_plate': { key: 'bg_plate', file: 'assets/processed/environment/ancient_ruins_bg.png', w: 1672, h: 941, family: 'deco', colliders: [], openings: [] },
  'fg_tl_branch': { key: 'fg_tl_branch', file: 'assets/processed/foreground/garden_tl_branch.png', w: 661, h: 258, family: 'deco', colliders: [], openings: [] },
  'fg_tr_column': { key: 'fg_tr_column', file: 'assets/processed/foreground/garden_tr_column.png', w: 604, h: 357, family: 'deco', colliders: [], openings: [] },
  'fg_bl_arch': { key: 'fg_bl_arch', file: 'assets/processed/foreground/garden_bl_arch.png', w: 401, h: 565, family: 'deco', colliders: [], openings: [] },
  'fg_br_column': { key: 'fg_br_column', file: 'assets/processed/foreground/garden_br_column.png', w: 435, h: 546, family: 'deco', colliders: [], openings: [] },
  'fg_ground': { key: 'fg_ground', file: 'assets/processed/foreground/garden_ground_strip.png', w: 1672, h: 264, family: 'deco', colliders: [], openings: [] },
}
